import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import ThemeProvider from "@/components/ThemProvider";
import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/MobileNavbar";
import LogOutBtn from "@/components/LogOutBtn";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata = {
    title: "my social media App",
    description: "Generated by create next app",
    icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logo.svg",
        href: "/logo.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logo-dark.svg",
        href: "/logo-dark.svg",
      }
    ]
  }
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}>
                <ThemeProvider 
                    ThemeProvider
                    disableTransitionOnChange
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <Navbar />
                    
                    <MobileNavbar>
                        <LogOutBtn /> 
                    </MobileNavbar>
                    
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
